package com.telecominfraproject.wlan.equipmentgateway.models;

public class CEGWChangeRedirectorHost extends EquipmentCommand {
	
	/**
     * Autogenerated
     */
    private static final long serialVersionUID = -2625034731537788892L;
    
    /**
     * Redirector host
     */
    private String redirectorHost;
    

    /**
     * Constructor
     * 
     * @param inventoryId
     * @param equipmentId
     * @param redirectorHost
     */
    public CEGWChangeRedirectorHost(String inventoryId, long equipmentId, String redirectorHost) {
        super(CEGWCommandType.ChangeRedirectorHost, inventoryId, equipmentId);
        this.setRedirectorHost(redirectorHost);
    }

    /**
     * Constructor used by JSON
     */
    public CEGWChangeRedirectorHost() {
        super(CEGWCommandType.ChangeRedirectorHost, null, 0);
    }

    public String getRedirectorHost() {
        return redirectorHost;
    }

    public void setRedirectorHost(String redirectorHost) {
        this.redirectorHost = redirectorHost;
    }
    
    @Override
    public boolean hasUnsupportedValue() {
        if (super.hasUnsupportedValue()) {
            return true;
        }
        return false;
    }
}
