drop table equipment if exists;

create table equipment (
     -- hsqldb 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customerId int,
    profileId bigint,
    locationId bigint,
    equipmentType int,
    inventoryId varchar(100) unique not null,
    
    name varchar(50),
    details varbinary(65535),
    
    createdTimestamp bigint not null,
    lastModifiedTimestamp bigint not null
  
);

create index equipment_customerId on equipment (customerId);
create index equipment_customerId_equipmentType on equipment (customerId, equipmentType);  
create index equipment_profileId on equipment (profileId);  
create index equipment_inventoryId on equipment (inventoryId);
create index equipment_location on equipment (locationId);
