drop table status if exists;

create table status (
     -- hsqldb 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customerId int,
    equipmentId bigint,
    statusDataType int not null,
    details varbinary(65535),
    
    createdTimestamp bigint not null,
    lastModifiedTimestamp bigint not null
  
);

create index status_customerId on status (customerId);
create index status_equipmentId on status (equipmentId);
create index status_customerEquipmentDatatype on status (customerId, equipmentId, statusDataType);


