drop table profile if exists;

create table profile (
     -- hsqldb 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customerId int,
    profileType int,
    name varchar(255),

    details varbinary(65535),
    
    createdTimestamp bigint not null,
    lastModifiedTimestamp bigint not null
  
);

create index idx_profile_customerId on profile (customerId);
create unique index if not exists idx_profile_customerId_profileType_name on profile (customerId, name, profileType); 


create table profile_map (
    customerId int,
    parentProfileId bigint, 
    childProfileId bigint,
    
    FOREIGN KEY (parentProfileId) REFERENCES profile(id) ON DELETE CASCADE,
    FOREIGN KEY (childProfileId) REFERENCES profile(id) ON DELETE CASCADE    
);

create index idx_profile_map_customerId on profile_map (customerId);
create index idx_profile_map_customerId_parent on profile_map (customerId, parentProfileId);
create index idx_profile_map_parent on profile_map (parentProfileId);
create index idx_profile_map_child on profile_map (childProfileId);