CREATE USER tip_user WITH
  LOGIN
  SUPERUSER
  CREATEDB
  CREATEROLE
  INHERIT
  NOREPLICATION
  CONNECTION LIMIT -1
  VALID UNTIL '2025-04-03T11:50:38+05:30'
  PASSWORD 'tip_password';
\l ;

SELECT 'CREATE DATABASE prov_db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prov_db')\gexec

GRANT ALL PRIVILEGES ON DATABASE prov_db TO tip_user;

